name: "Build"
on:
  pull_request:
    paths-ignore: &IGN_PATHS
      - 'README.md'
      - '.gitignore'
  push:
    paths-ignore: *IGN_PATHS
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@master
      with:
        nix_path: nixpkgs=channel:nixos-20.03
    - run: nix-build

