name: "Build"
on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
    paths-ignore:
      - "README.md"
      - ".gitignore"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build --arg version '"${{ github.sha }}"'
